include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    invalid_assignment: false
    argument_type_not_assignable: false
    avoid_function_literals_in_foreach_calls: false